#!/bin/bash
# Usage Example: `quiz grep`
IFS=$'\n'
filename=$1
quiz_root=$(dirname $(realpath $0 ))


red='\x1b[31m \n'
yellow='\x1b[33m \n'
blue='\e[1;34m \n'
clear='\e[0m'
clear2='\e[0m \n\n'

user_answer="${yellow}Your answer: $clear"
correct_answer="${yellow}Correct answer: $clear"

true="${blue}Correct!$clear2"
false="${red}false!$clear2"


case "$1" in
grep|egrep)
	for line in $(cat $quiz_root/$1); do
		question="$yellow"$(cut -d '&' -f 2 <<<"$line")"$clear2"
		printf $question;
		while read -p "enter command: " input ; do
			raw_answer=$(cut -d '&' -f 1 <<<"$line")
			output=$(eval $input)
			answer=$(eval $raw_answer)
		 	if [ "$input" = "$answer" ]; then
			 	printf $true
			 	break
			else
			 	printf $user_answer"$output \n\n"
			 	printf $correct_answer"$answer \n\n"
			 	printf $false
			 	printf $question
			 	line=$(grep -n "$answer" $1 |cut -f1 -d:)
			 	ex -s -c "$line"m0 -c wq $1
			fi
		done
	done ;;
cron) 
	for line in $(cat $quiz_root/$1); do
		question="$yellow"$(cut -d '&' -f 2 <<<"$line")"$clear2"
		printf $question;
		while read -p "enter command: " input ; do
			answer=$(cut -d '&' -f 1 <<<"$line")
		 	if [ $input = $answer ]; then
			 	printf $true
			 	break
			else
			 	printf $user_answer"$input \n\n"
			 	printf $correct_answer"$answer \n\n"
			 	printf $false
			 	printf $question
			 	line=$(grep -n "$answer" $1 |cut -f1 -d:)
			 	ex -s -c "$line"m0 -c wq $1
			fi
		done
	done ;;
*)
	echo 'Follow the command with the name of the unit you are working on. (eg. grep, egrep, cron, etc.)'
esac