# Sidebar navigation

- label: Basics
  items:
    - label: 'Documentation'
      link: '/basics/documentation'
    - label: 'Downloding Files'
      link: '/basics/downloading-files'
    - label: 'Archiving & Compression'
      link: '/basics/archiving-and-compression'
    - label: 'grep'
      link: '/basics/grep'
    - label: 'Finding Files'
      link: '/basics/finding-files'
    - label: 'cron'
      link: '/basics/cron'
    - label: 'Processes'
      link: '/basics/processes'
    - label: 'Logging'
      link: '/basics/logging'
    - label: 'File Manipulation'
      link: '/basics/file-manipulation'
    - label: 'Users & Permissions'
      link: '/basics/users-and-permissions'
    - label: 'Access Control Lists (ACL)'
      link: '/basics/access-control-lists-acl'
    - label: 'Package Management'
      link: '/basics/package-management'
    - label: 'Git'
      link: '/basics/git'
    - label: 'Swap'
      link: '/basics/swap'
    - label: 'Basic Scripting'
      link: '/basics/basic-scripting'
- label: Containers and Virtualization
  items:
    - label: 'Linux Containers (LXC)'
      link: '/containers-and-virtualization/linux-containers-lxc'
    - label: 'Docker'
      link: '/containers-and-virtualization/docker'
    - label: 'Kernel-based Virtual Machine (KVM)'
      link: '/containers-and-virtualization/kernel-based-virtual-machine-kvm'
- label: Networking
  items:
    - label: 'Routing'
      link: '/networking/routing'
    - label: 'Domain Name Servers (DNS)'
      link: '/networking/domain-name-servers-dns'
    - label: 'Firewall'
      link: '/networking/firewall'
    - label: 'Web Servers'
      link: '/networking/web-servers'
    - label: 'Secure Shell (SSH)'
      link: '/networking/secure-shell-ssh'
    - label: 'Network File System (NFS), Samba (SMB), and File Transfer Protocol (FTP)'
      link: '/networking/network-file-system-nfs-samba-smb-and-file-transfer-protocol-ftp'
    - label: 'Email'
      link: '/networking/email'
    - label: 'Time servers'
      link: '/networking/time-servers'
    - label: 'Single Sign On (SSO)'
      link: '/networking/single-sign-on-sso'
    - label: 'Network Scripting'
      link: '/networking/network-scripting'
- label: Storage
  items:
    - label: 'Rsync'
      link: '/storage/rsync'
    - label: 'Disk Quotas'
      link: '/storage/disk-quotas'
    - label: 'Logical Volume Management (LVM)'
      link: '/storage/logical-volume-management-lvm'
    - label: 'Redundant Array of Independent Disks (RAID)'
      link: '/storage/redundant-array-of-independent-disks-raid'
    - label: 'Linux Unified Key Setup (LUKS)'
      link: '/storage/linux-unified-key-setup-luks'
    - label: 'Storage Scripting'
      link: '/storage/storage-scripting'
- label: Booting and Deep System
  items:
    - label: 'Grand Unified Boot Loader (GRUB)'
      link: '/boot-and-deep-system/grand-unified-boot-loader-grub'
    - label: 'Systemd'
      link: '/boot-and-deep-system/systemd'
    - label: 'Kernel Runtime Parameters'
      link: '/boot-and-deep-system/kernel-runtime-parameters'
    - label: 'AppArmor'
      link: '/boot-and-deep-system/apparmor'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/danielclough/Linux-Sysadmin-Test-Prep
    - label: 'Copyright'
      link: https://github.com/danielclough/Linux-Sysadmin-Test-Prep/blob/main/LICENSE


# - label: 
#   items:    
#     - label: ''
#       link: '//'